import Head from "next/head";
import Layout from "@/Components/Layout/Layout";
import HomeScreen from "@/Components/HomeScreen/HomeScreen";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gym Baran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeScreen />
    </>
  );
}
